apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: my-space
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: 'nginx:1.14.1'
          name: nginx
          ports:
            - containerPort: 80
